service: career-compass-api
frameworkVersion: "4.x"
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: prod

  environment:
    NODE_ENV: production

    # Database
    DATABASE_URL_PROD: ${env:DATABASE_URL_PROD}
    DATABASE_URL_DEV: ${env:DATABASE_URL_DEV}

    # Frontend
    FRONTEND_URL_PROD: ${env:FRONTEND_URL_PROD}
    FRONTEND_URL_DEV: ${env:FRONTEND_URL_DEV}

    # Auth
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}

plugins:
  - serverless-offline

functions:
  api:
    handler: lambda.handler
    timeout: 30
    memorySize: 512
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY